spring.application.name=Netlab-BulletHellShootEmUp-BE-netlab
spring.datasource.url=jdbc:postgresql://ep-summer-base-azh1xqbt-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_mvCMrqQS40LE&sslmode=require&channelBinding=require
spring.jpa.properties.jakarta.persistence.jdbc.url=jdbc:postgresql://ep-summer-base-azh1xqbt-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_mvCMrqQS40LE&sslmode=require&channelBinding=require
