spring.application.name=Netlab-BulletHellShootEmUp-BE-netlab
spring.datasource.url=jdbc:postgresql://ep-summer-base-azh1xqbt-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_mvCMrqQS40LE&sslmode=require&channelBinding=require

# Tambahkan konfigurasi ini agar koneksi tidak terputus/hang
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true